{{- if .Values.authorizer.database_url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-url
type: Opaque
data:
  database_url: "{{ .Values.authorizer.database_url | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_host }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-host
type: Opaque
data:
  database_host: "{{ .Values.authorizer.database_host | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-username
type: Opaque
data:
  database_username: "{{ .Values.authorizer.database_username | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password
type: Opaque
data:
  database_password: "{{ .Values.authorizer.database_password | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-cert
type: Opaque
data:
  database_cert: "{{ .Values.authorizer.database_cert | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_cert_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-cert-key
type: Opaque
data:
  database_cert_key: "{{ .Values.authorizer.database_cert_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_ca_cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-ca-cert
type: Opaque
data:
  database_ca_cert: "{{ .Values.authorizer.database_ca_cert | b64enc }}"
{{- end }}
{{- if .Values.authorizer.redis_url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-url
type: Opaque
data:
  redis_url: "{{ .Values.authorizer.redis_url | b64enc }}"
{{- end }}
{{- if .Values.authorizer.aws_access_key_id }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id
type: Opaque
data:
  aws_access_key_id: "{{ .Values.authorizer.aws_access_key_id | b64enc }}"
{{- end }}
{{- if .Values.authorizer.aws_secret_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
type: Opaque
data:
  aws_secret_access_key: "{{ .Values.authorizer.aws_secret_access_key | b64enc }}"
{{- end }}