{{- if .Values.authorizer.database_url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-url
type: Opaque
data:
  database_url: "{{ .Values.authorizer.database_url | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_host }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-host
type: Opaque
data:
  database_host: "{{ .Values.authorizer.database_host | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-username
type: Opaque
data:
  database_username: "{{ .Values.authorizer.database_username | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-password
type: Opaque
data:
  database_password: "{{ .Values.authorizer.database_password | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-cert
type: Opaque
data:
  database_cert: "{{ .Values.authorizer.database_cert | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_cert_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-cert-key
type: Opaque
data:
  database_cert_key: "{{ .Values.authorizer.database_cert_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.database_ca_cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: database-ca-cert
type: Opaque
data:
  database_ca_cert: "{{ .Values.authorizer.database_ca_cert | b64enc }}"
{{- end }}
{{- if .Values.authorizer.redis_url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-url
type: Opaque
data:
  redis_url: "{{ .Values.authorizer.redis_url | b64enc }}"
{{- end }}
{{- if .Values.authorizer.client_id }}
---
apiVersion: v1
kind: Secret
metadata:
  name: client-id
type: Opaque
data:
  client_id: "{{ .Values.authorizer.client_id | b64enc }}"
{{- end }}
{{- if .Values.authorizer.client_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: client-secret
type: Opaque
data:
  client_secret: "{{ .Values.authorizer.client_secret | b64enc }}"
{{- end }}
{{- if .Values.authorizer.admin_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  admin_secret: "{{ .Values.authorizer.admin_secret | b64enc }}"
{{- end }}
{{- if .Values.authorizer.jwt_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt_secret: "{{ .Values.authorizer.jwt_secret | b64enc }}"
{{- end }}
{{- if .Values.authorizer.jwt_private_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-private-key
type: Opaque
data:
  jwt_private_key: "{{ .Values.authorizer.jwt_private_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.jwt_public_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-public-key
type: Opaque
data:
  jwt_public_key: "{{ .Values.authorizer.jwt_public_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.aws_access_key_id }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key-id
type: Opaque
data:
  aws_access_key_id: "{{ .Values.authorizer.aws_access_key_id | b64enc }}"
{{- end }}
{{- if .Values.authorizer.aws_secret_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret-access-key
type: Opaque
data:
  aws_secret_access_key: "{{ .Values.authorizer.aws_secret_access_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.twilio_account_sid }}
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-account-sid
type: Opaque
data:
  twilio_account_sid: "{{ .Values.authorizer.twilio_account_sid | b64enc }}"
{{- end }}
{{- if .Values.authorizer.twilio_api_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-api-key
type: Opaque
data:
  twilio_api_key: "{{ .Values.authorizer.twilio_api_key | b64enc }}"
{{- end }}
{{- if .Values.authorizer.twilio_api_secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: twilio-api-secret
type: Opaque
data:
  twilio_api_secret: "{{ .Values.authorizer.twilio_api_secret | b64enc }}"
{{- end }}
{{- if .Values.authorizer.smtp_username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-username
type: Opaque
data:
  smtp_username: "{{ .Values.authorizer.smtp_username | b64enc }}"
{{- end }}
{{- if .Values.authorizer.smtp_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-password
type: Opaque
data:
  smtp_password: "{{ .Values.authorizer.smtp_password | b64enc }}"
{{- end }}
