{{- if not .Values.authorizer.redis_url }}
{{- if .Values.redis.install }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: 'redis'
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          command: ['redis-server', '--appendonly', 'yes']
          ports:
            - containerPort: 6379
              name: web
          volumeMounts:
            - name: redis
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "{{ .Values.redis.storageClassName | default "standard" }}"
        resources:
          requests:
            storage: "{{ .Values.redis.storage | default "5Gi" }}"
{{- end }}
{{- end }}